### PR TITLE
Issue 461: Update login page

### PR DESCRIPTION
**Pull request by anilnatha**
This pull request includes:

1. Updated `loginProviders.html` to fix an issue with the rendering of the UI on UAT where the ESA-API registered service is configured and shouldn't be displayed to the user.
2. Added additional makefile recipes for repeated tasks.
3. Added volume mount to `docker-compose.yml` so that config settings can be modified without having to rebuild the CAS image. This does require the Tomcat service to be restarted, which a make target was added to facilitate the restart.

@bsatoriu I've successfully deployed this to DIT. Since I don't have access to deploy to UAT, could you please review this code, and if it looks good, merge it in and deploy the WAR file that is on DIT located at `~/cas.war` to UAT?

### CODE REVIEW

**Comment by bsatoriu** [comment]
Looks good @anilnatha. This is deployed to UAT.

**Comment by anilnatha** [comment]
Thanks @bsatoriu.  I take it you didn't come across any errors in the logs like we did during the first deployment?

Also, were you still planning on updating the description we observed in UAT, "MAAP API 10000- wildcard."

**Comment by bsatoriu** [comment]
@anilnatha, I just updated the service name and description on UAT.

I actually came across an issue building the docker image locally (see exception below). Might be a configuration problem on my side. I'll DM you if I need help getting that resolved.

```
bsatoriu@RAYL-C01304 maap-auth-cas % sudo make build-images -f makefile 
Password:
docker-compose build
Building cas
[+] Building 127.8s (11/32)                                                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 2.58kB                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 72B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                                                           3.2s
 => [internal] load build context                                                                                                                                                                         0.0s
 => => transferring context: 640.72kB                                                                                                                                                                     0.0s
 => [ 1/28] FROM docker.io/library/ubuntu:18.04@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79dbbacddd7d6                                                                                   4.5s
 => => resolve docker.io/library/ubuntu:18.04@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79dbbacddd7d6                                                                                     0.0s
 => => sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79dbbacddd7d6 1.41kB / 1.41kB                                                                                                            0.0s
 => => sha256:fc0d6af5ab38dab33aa53643c4c4b312c6cd1f044c1a2229b2743b252b9689fc 529B / 529B                                                                                                                0.0s
 => => sha256:5a214d77f5d747e6ed81632310baa6190301feeb875cf6bf9da560108fa09972 1.46kB / 1.46kB                                                                                                            0.0s
 => => sha256:284055322776031bac33723839acb0db2d063a525ba4fa1fd268a831c7553b26 26.71MB / 26.71MB                                                                                                          3.0s
 => => extracting sha256:284055322776031bac33723839acb0db2d063a525ba4fa1fd268a831c7553b26                                                                                                                 1.4s
 => [ 2/28] RUN apt-get update && apt-get install -y default-jdk supervisor curl && rm -rf /var/lib/apt/lists/* && apt-get clean                                                                        118.2s
 => [ 3/28] RUN groupadd tomcat                                                                                                                                                                           0.3s 
 => [ 4/28] RUN useradd -s /bin/false -g tomcat -d /home/tomcat tomcat                                                                                                                                    0.4s 
 => [ 5/28] WORKDIR /tmp                                                                                                                                                                                  0.0s 
 => [ 6/28] RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz                                                                                                  0.6s 
 => ERROR [ 7/28] RUN echo "83430f24d42186ce2ff51eeef2f7a5517048f37d9050c45cac1e3dba8926d61a1f7f5aba122a34a11ac1dbdd3c1f6d98671841047df139394d43751263de57c3 /tmp/apache-tomcat-9.0.54.tar.gz" | sha512s  0.4s 
------                                                                                                                                                                                                         
 > [ 7/28] RUN echo "83430f24d42186ce2ff51eeef2f7a5517048f37d9050c45cac1e3dba8926d61a1f7f5aba122a34a11ac1dbdd3c1f6d98671841047df139394d43751263de57c3 /tmp/apache-tomcat-9.0.54.tar.gz" | sha512sum -c -:      
#10 0.401 sha512sum: WARNING: 1 computed checksum did NOT match
#10 0.401 /tmp/apache-tomcat-9.0.54.tar.gz: FAILED
------
executor failed running [/bin/sh -c echo "${SHA} /tmp/apache-tomcat-9.0.54.tar.gz" | sha512sum -c -]: exit code: 1
ERROR: Service 'cas' failed to build : Build failed
make: *** [build-images] Error 1
```

**Comment by anilnatha** [comment]
@bsatoriu The URL used to download Apache tomcat is returning a 404 at the moment. I've had this happen on other projects when needing to download Apache files where it intermittently goes down and comes back online randomly.

**Comment by anilnatha** [comment]
@bsatoriu Looks like Tomcat v9.0.54 was deleted from their server and v9.0.56 is available: 

https://dlcdn.apache.org/tomcat/tomcat-9/

**Comment by anilnatha** [comment]
@bsatoriu I have found another location where they store their binaries that persists older versions.

I'll get this fixed and push it out so you can test the docker config.

**Pull request merged**
