### PR TITLE
Issue 461 - Update Login Page

### PR DESCRIPTION
**Pull request by anilnatha**
Notable updates in this build:

1) Reskinned login page
2) Dockerized Apache and CAS services to facilitate local development without needing to spend much time getting developer machine configured.
    * **NOTE:** Syncope services are not yet dockerized as the focus here was to get the minimal configuration created to update the login page
3) Added Makefile with numerous recipes to accelerate development.

@bsatoriu Before we merge this in I would like to review what I did, as this will affect your future deployments, and get some guidance on what I should update in the README.

### CODE REVIEW

**Comment by bsatoriu** [comment]
@anilnatha great work on the UI changes and added Docker support. I created a sample README revision if you wanted to an idea on integrating the new Docker instructions: https://github.com/MAAP-Project/maap-auth-cas/blob/readme-revision/README.md

I think it would be a good idea to integrate the Postgres/Syncope components into Docker at some point, after which we could consolidate the README with just AWS deployment using Docker.

**Review by bsatoriu — APPROVED** [review]

**Comment by anilnatha** [comment]
@bsatoriu Thank you for the quick turnaround and for creating the sample README.  I'll add in the parts I need to and commit those so we can work them into this pull request.

Any ideas on how we can address the change needed for the CAS Tomcat server XML file to run locally vs on AWS?

**Comment by anilnatha** [comment]
@bsatoriu I've updated the README file with local development information.

If all is good, can we merge in the code and try deploying to DIT? I'm curious to see how you may use this updated environment for deployments.

**Comment by bsatoriu** [comment]
Sounds good, @anilnatha. Let me know if you'd like to deploy to DIT together or if you feel comfortable deploying yourself and looping me in when needed.

**Comment by anilnatha** [comment]
@bsatoriu Let's deploy together for this first time since I'm not yet familiar with our AWS configuration. I'll book something on our calendar based on our availability.

**Pull request merged**
